<?php




class Cylinder extends Circle
{
protected $height;
function __construct($name, $radius,$height)
{
    parent::__construct($name, $radius);
    $this->height=$height;
}
function getArea()
{
    return parent::getArea()*2+parent::getPerimeter()*$this->height; // TODO: Change the autogenerated stub
}
function getVolum(){
    return parent::getArea()*$this->height;
}
}